add G3S_pre to RUN, change main to run G3S_start automately

diff --git a/GlassSea/sys/util/RUN b/GlassSea/sys/util/RUN
--- a/GlassSea/sys/util/RUN
+++ b/GlassSea/sys/util/RUN
@@ -11,6 +11,21 @@ echo "        `date`"
 echo "        `pwd`"
 echo '          *   *   *   *   *   *   *   *   *  '
 
+if ( -x "./G3S_pre" ) then
+	echo "    Running this part's G3S_pre"
+	echo RUNNING > ./G3S_status
+	if ( -x "./G3S_runrc.csh" ) then
+		source ./G3S_runrc.csh
+	endif
+	./G3S_pre
+	set pre_res = $?
+	if ( $pre_res != 0 ) then
+		echo "    Error running G3S_pre"
+		echo FAILED > ./G3S_status
+		exit $pre_res
+	endif
+endif
+
 ${G3S}/sys/util/REQUIRE ./G3S_require
 set reqres = $?
 if ( "$reqres" != "0" ) then
@@ -21,8 +36,9 @@ else
 endif
 
 if ( -x "./G3S_run" ) then
+	echo "    Running this part's G3S_run"
 	echo RUNNING > ./G3S_status
-	if ( -e "./G3S_runrc.csh" ) then
+	if ( -x "./G3S_runrc.csh" ) then
 		source ./G3S_runrc.csh
 	endif
 	./G3S_run
@@ -32,6 +48,7 @@ else
 endif
 
 if ( -x "./G3S_check" ) then
+	echo "    Checking this part's result"
 	./G3S_check
 	set chkres = $?
 else
@@ -39,9 +56,11 @@ else
 endif
 
 if ( "$runres" == "0" && "$chkres" == "0" ) then
+	echo "    SUCCESS! "
 	echo SUCCESS > ./G3S_status
 	exit 0
 else
+	echo "    FAILED! "
 	echo FAILED > ./G3S_status
 	exit 1
 endif
